### PR TITLE
[13.0][ADD] account_due_list_commercial_effect_group_account

### PR DESCRIPTION
**Pull request by ChristianSantamaria**
Adds new field in Account Group commercial_effect and improve action in menuitem "Payment and due list"

### CODE REVIEW

**Comment by ChristianSantamaria** [comment]
@lmiguens-solvos @dalonsod, its installed in alu enviroment test, can u test it?

**Comment by ChristianSantamaria** [comment]
EOF line fixed
oca_dependencie -> account_payment already added
Fix name search view
Add comment in the filter

**Review by dalonsod — APPROVED** [review]
Code review :+1: 

@lmiguens-solvos if you're made a functional review in AluTest environment and it's OK, I'll merge it

**Comment by lmiguens-solvos** [comment]
LGTM. Tested in alu enviroment test

**Pull request merged**
