### PR TITLE
[13.0][IMP] account_security_extra: move payment terms menu

### PR DESCRIPTION
**Pull request by IriaAlonso**
- Change the menu position "Invoicing/Configuration/Invoicing/Payment Terms" to "Invoicing/Accounting/Management/Payment Terms"
- Change permissions to users “Show full accounting features”

@dalonsod

### CODE REVIEW

**Review by dalonsod — CHANGES_REQUESTED** [review]
Required changes:
- Add to existing uninstall hook the action that takes menu back to its original location.
- `README.rst` and `index.html` file should be included in a standalone `[UPD] account_security_extra: README & index` commit as usual when some `readme` information has changed.

**Comment by IriaAlonso** [comment]
@dalonsod changes done :+1:

**Comment by dalonsod** [comment]
@ChristianSantamaria could you install this improvement in AluTest enviroment?

**Comment by ChristianSantamaria** [comment]
Done :+1:

**Comment by dalonsod** [comment]
Two changes made:
* Added twin ACL for `account.payment.term.line` model (details for each `account.payment.term`).
* Improved ACL descriptions.

**Pull request merged**
